#include<stdio.h>
int main()
int arr[5];
int arrodd [5];
int count= 0;
printf("enter number");
for(int i=0;i<5;i++)
{
scanf("%d",&arr[i]);
}
for(int j=1;j<5;j++)
{
if(arr[j]%2!=0)
{
arrodd [count]=arr[j];
count++;
}
}
printf(" total number %d");
for(int j=1;j<5;j++)
{ printf("\n odd number %d",arr[j]);
}
printf("\n total odd number ");
for(int k=0;k<count;k++)
{
| printf("%d",arrodd[k]);
}
return 0;